spring:
logging:
  level:
    org.springframework.web: DEBUG

server:
  port: 8080

zuul:
  routes:
    api:
      path: /api/blogposts/**
      url: http://localhost:8082/

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

ribbon:
  eureka:
    enabled: false

flyway:
  enabled: false
