spring:
  application:
    name: jvcdp-ui
logging:
  level:
    org.springframework.web: DEBUG

server:
  port: 8081

zuul:
  routes:
    serverstats:
      path: /api/serverstats/**
      serviceId: serverstats

serverstats:
  ribbon:
    listOfServers: localhost:8082

ribbon:
  eureka:
    enabled: false

flyway:
  enabled: false
