spring:
  application:
    name: jvcdp-ui

logging:
  level:
    org.springframework.web: DEBUG

server:
  port: 8080

zuul:
  routes:
    api:
      path: /api/serverstats/**
      serviceId: jvcdp-serverstats

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka

ribbon:
  eureka:
    enabled: true

flyway:
  enabled: false
